project:
  type: website
  output-dir: docs
resources:
  - CNAME
website:
  sidebar: 
    logo: logo/omi_logo.png
    search: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - brand
    css: styles.css
    toc: false