project:
  type: website

website:
  title: "Open Market Intelligence Data Analytics & Automation"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



